### ISSUE TITLE
Unclear/missing documentation

### ISSUE THREAD

**Issue by tibel** [Caliburn-Micro/caliburn-micro.github.io#9]
- [ ] `ActionMessage.AssocicatedObject` is not automatically set on win81/wpa81 (see Caliburn-Micro/Caliburn.Micro#24)
- [ ] `FrameAdapter.CanCloseOnNavigating()` on phone (Caliburn-Micro/Caliburn.Micro#17)
- [ ] design time support in WinRT (Caliburn-Micro/Caliburn.Micro#2)
- [ ] logging (Caliburn-Micro/Caliburn.Micro#14)
- [ ] conductors and activation/deactivation of child view models (Caliburn-Micro/Caliburn.Micro#1)
